language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - jruby-19mode # JRuby in 1.9 mode
before_install:
  - gem install bundler -v '= 1.11.2'
  - gem update --system
  - gem --version
